### ISSUE TITLE
Crash when trying to record ARCL 

### ISSUE THREAD

**Issue by francisjervis** [svtek/SceneKitVideoRecorder#12] opened 2017-09-18 18:59 UTC
When trying to record a scene with https://github.com/ProjectDent/ARKit-CoreLocation/ I get the following error:

````
validateArgumentsForTextureViewOnDevice:1037: failed assertion `source texture pixelFormat (MTLPixelFormatRGB10A8_2P_XR10_sRGB) not compatible with texture view pixelFormat (MTLPixelFormatBGRA8Unorm).'
````

**Comment by okaris** [comment] 2017-09-19 04:33
Duplicate of #3

**Closed as completed by okaris** 2017-09-19 04:33 UTC
